#!/bin/sh
#
# Usage: script/run-tester
# Description: run tester container
#

BASE_DIRECTORY=`pwd`

cd ${BASE_DIRECTORY}/test/feature
docker kill tester > /dev/null 2>&1 || true
docker rm   tester > /dev/null 2>&1 || true
docker run \
  --rm \
  --name tester \
  -v $PWD/spec:/test/spec \
  -e TARGET_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' target) \
  quay.io/wantedly/infrataster
