#!/bin/sh
#
# Usage: script/run_tester
# Description: run tester container
#

BASE_DIRECTORY=`pwd`

cd ${BASE_DIRECTORY}/test/feature
docker run \
  -v $PWD/spec:/test/spec \
  -e TARGET_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' target) \
  quay.io/wantedly/infrataster
