#!/bin/sh
#
# Usage: script/cibuild
# Description: script to run test
#

set -e

# this script should be run in project root
BASE_DIRECTORY=`pwd`
SERVER_NAME="image.example.com"

echo "==> Building target..."
cd ${BASE_DIRECTORY}
script/build

echo "==> Running nginx-image-server..."
docker kill nginx-image-server > /dev/null 2>&1 || true
docker rm   nginx-image-server > /dev/null 2>&1 || true
docker kill infrataster > /dev/null 2>&1 || true
docker rm   infrataster > /dev/null 2>&1 || true
script/run -d

echo "==> Running test..."
script/run-infrataster

echo "==> Cleaning up..."
docker kill nginx-image-server > /dev/null 2>&1 || true
docker rm   nginx-image-server > /dev/null 2>&1 || true
docker kill infrataster > /dev/null 2>&1 || true
docker rm   infrataster > /dev/null 2>&1 || true
