#!/bin/sh
#
# Usage: script/cibuild
# Description: script to run test
#

set -e

# this script should be run in project root
BASE_DIRECTORY=`pwd`
SERVER_NAME="image.example.com"

echo "==> Building target..."
cd ${BASE_DIRECTORY}
docker build -t target .

echo "==> Running target..."
script/run_target -d

echo "==> Running tester..."
script/run_tester

echo "==> Cleaning up..."
docker kill target > /dev/null 2>&1 || true
docker rm   target > /dev/null 2>&1 || true
docker kill tester > /dev/null 2>&1 || true
docker rm   tester > /dev/null 2>&1 || true
